name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Setup python envoirnment for 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        ./manage.py test
        coverage run manage.py test
        coverage report
        coverage xml
    - name: Coverage report
      uses: 5monkeys/cobertura-action@v12
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          fail_below_threshold: True
          minimum_coverage: 75
          show_missing: True
          path: coverage.xml