name: ci

on:
  pull_request:
    branches: "master"
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.0.0
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run Tests
      env:
          SECRET_KEY: fake_key
          DEBUG: True
      run: |
        coverage run manage.py test
        coverage xml
    - name: Show report
      uses: 5monkeys/cobertura-action@v12
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 70