name: ci

on:
  pull_request:
    branches: "master"
  push:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.0.0
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        coverage run manage.py test
        coverage report
        coverage xml
    - name: Coverage report
      uses: 5monkeys/cobertura-action@v12
      with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         fail_below_threshold: True
         minimum_coverage: 70
         show_missing: True
         path: coverage.xml